
app:
  jwt-secret-name: "JWT/secret"
  aws-secret-region: "us-east-2"

spring:
  jpa:
    properties:
      hibernate:
        boot:
          allow_jdbc_metadata_access: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
        
        
logging:
  level:
    root: WARN
    org.springframework.web: WARN
    com.RecipesApplication: INFO


#spring.jpa.hibernate.ddl-auto=none
#spring.sql.init.mode=never