
app:
  jwt-secret-name: "JWT/secret"
  aws-secret-region: "us-east-2"
  s3-bucket-name: "fargopolis-bucket"

spring:
  jpa:
    properties:
      hibernate:
        boot:
          allow_jdbc_metadata_access: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
        
        
logging:
  level:
    root: WARN
    org.springframework.web: WARN
    com: INFO


#spring.jpa.hibernate.ddl-auto=none
#spring.sql.init.mode=never