import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.scss'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
        <body className={inter.className}>
            <div className="sidebar">
                <Link href='/'>Fargod's Wonder Emporium</Link>
                <Link href='/recipes'>Recipes</Link>
            </div>
            {children}
        </body>
    </html>
  )
}
