name: Deploy Latest Image on EC2 instance

on:
  workflow_dispatch:
    inputs:
      can_write:
        description: 'Whether this deployment allows writing'
        required: false
        default: true

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Run script already on EC2
        run: |
          ssh -i ../EC2_Fargopolis_KeyPair.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} 'bash ./deploy-latest.sh ${{ github.event.inputs.can_write }}'
